@MiWebApi8_HostAddress = http://localhost:5136

POST {{MiWebApi8_HostAddress}}/api/User/PostUsuario
Content-Type: application/json

{
  "nombre": "Juan",
  "edad": 30,
  "identificacion": "123456789",
  "direcciones": [
    {
      "direccionCompleta": "Calle 123 #45-67"
    },
    {
      "direccionCompleta": "Avenida Siempre Viva 742"
    }
  ]
}
